AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Lambda Pipeline P1
Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Runtime: python3.8
Resources:
  LambdaSearch:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: auto-search-photos
      Handler: lambda_function.lambda_handler
      CodeUri: ./search-photos.py
      Description: 'Lambda search photos function for our HW3 stack'
      Role: 'arn:aws:iam::416562561820:role/service-role/LF2-role-gtoil4v7'
      Environment:
        Variables:
          REGION: us-east-1
  LambdaIndex:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: auto-index-photos
      Handler: lambda_function.lambda_handler
      CodeUri: ./index-photos.py
      Description: 'Lambda index photos function for our HW3 stack'
      Role: 'arn:aws:iam::416562561820:role/service-role/index-photos-role-ljptehrr'
      Environment:
        Variables:
          REGION: us-east-1
  LambdaDelete:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: auto-delete-photos
      Handler: lambda_function.lambda_handler
      CodeUri: ./delete-photos.py
      Description: 'Lambda delete photos function for our HW3 stack'
      Role: 'arn:aws:iam::416562561820:role/service-role/delete-photos-role-9wgllhee'
      Environment:
        Variables:
          REGION: us-east-1
  Bucket:
    Type: AWS::S3::Bucket
    DependsOn: BucketPermission
    Properties:
      BucketName: coms6998-b2
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: 's3:ObjectCreated:*'
            Function: !GetAtt LambdaIndex.Arn