AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Lambda Pipeline P1
Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Runtime: python3.6 
Resources:
  IndexLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: auto-index-photos
      Handler: lambda_function.lambda_handler
      CodeUri: ./index-photos.py
      Description: 'Lambda index photos function for our HW3 stack'
      Role: 'arn:aws:iam::416562561820:role/service-role/index-photos-role-ljptehrr'
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /getazs
            Method: get
      Environment:
        Variables:
          REGION: us-east-1
  DeleteLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: auto-delete-photos
      Handler: lambda_function.lambda_handler
      CodeUri: ./delete-photos.py
      Description: 'Lambda delete photos function for our HW3 stack'
      Role: 'arn:aws:iam::416562561820:role/service-role/delete-photos-role-9wgllhee'
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /getazs
            Method: get
      Environment:
        Variables:
          REGION: us-east-1
